#!/usr/bin/env bash

uinst=`sudo pacman -Qs | grep -E "^local" | fzf ${FZF_DEFAULT_OPTS} -m --header="[Pacman:uninstall]"`

uinst=${uinst#*/}
uinst=${uinst%% *}

if [[ -n "$uinst" ]]; then
    sudo pacman -Rns "$uinst"
fi
