
# 加载环境变量
source $HOME/.config/zsh/env.zsh

# ZSH_THEME="steeef"
ZSH_THEME="awesomepanda"
# ZSH_THEME="gozilla"

# 刷新自动补全
zstyle ':completion:*' rehash true

# 系统目录 $ZSH/plugins 自定义目录$ZSH/custom/plugins
plugins=(git
    sudo 
    web-search
    zsh-syntax-highlighting
    zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

[ -f "$ZSH_HOME/fzf.zsh" ] && source "$ZSH_HOME/fzf.zsh"

[ -f "$ZSH_HOME/aliases.zsh" ] && source "$ZSH_HOME/aliases.zsh"

[ -f "$ZSH_HOME/functions.zsh" ] && source "$ZSH_HOME/functions.zsh"

[ -f "$ZSH_HOME/mappings.zsh" ] && source $ZSH_HOME/mappings.zsh

