
# 加载环境变量
source $HOME/.config/zsh/env.zsh

source $OHMYZSH/oh-my-zsh.sh

[ -f "$ZSH_HOME/mappings.zsh" ] && source $ZSH_HOME/mappings.zsh

[ -f "$ZSH_HOME/fzf.zsh" ] && source "$ZSH_HOME/fzf.zsh"

[ -f "$ZSH_HOME/aliases.zsh" ] && source "$ZSH_HOME/aliases.zsh"

[ -f "$ZSH_HOME/functions.zsh" ] && source "$ZSH_HOME/functions.zsh"

# ZSH_THEME="steeef"
ZSH_THEME="awesomepanda"
# ZSH_THEME="gozilla"

# 刷新自动补全
zstyle ':completion:*' rehash true

# 系统目录 $ZSH/plugins 自定义目录$ZSH/custom/plugins
plugins=(git
    sudo 
    web-search
    zsh-syntax-highlighting
    zsh-autosuggestions
)


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/opt/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/opt/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

